# Root-level Cloudflare Pages configuration
name = "moonbirds-art-forge"
compatibility_date = "2024-01-01"

[deployment]
production_branch = "main"

[[pages]]
source = "moonforge/apps/web/dist"

[pages.build]
command = "cd moonforge && pnpm install --frozen-lockfile && cd apps/web && pnpm build"

[pages.environment]
NODE_VERSION = "20"