# Cloudflare Pages configuration
name = "moonlore"
compatibility_date = "2025-01-01"

[build]
command = "pnpm install && pnpm build"
working_directory = "/"
watch_paths = ["apps/**/*", "packages/**/*", "workers/**/*"]

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false

[[build.upload.rules]]
type = "Text"
globs = ["**/*.js", "**/*.css", "**/*.json", "**/*.html"]

# KV Namespace for sessions
[[kv_namespaces]]
binding = "SESSION"
id = "moonlore_session_kv"
preview_id = "moonlore_session_kv_preview"

# R2 Bucket for image storage
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "moonlore-images"
preview_bucket_name = "moonlore-images-preview"
fallthrough = true