name = "moonbirds-api-generate"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
workers_dev = false

[[kv_namespaces]]
binding = "GENERATED_IMAGES"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"

[ai]
binding = "AI"
