name = "moonbirds-api-generate"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
workers_dev = false

[[kv_namespaces]]
binding = "GENERATED_IMAGES"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"

[[kv_namespaces]]
binding = "PROMPT_CACHE"
id = "YOUR_PROMPT_CACHE_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_PROMPT_CACHE_ID"

[[kv_namespaces]]
binding = "MINT_RECORDS"
id = "YOUR_MINT_RECORDS_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_MINT_RECORDS_ID"

[ai]
binding = "AI"

[vars]
USE_DALLE_FALLBACK = "true"
